# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: v-router
site_description: A unified LLM interface that provides automatic fallback between different LLM providers
site_author: Ben Selleslagh
site_url: https://vectrix-ai.github.io/v-router

# Repository
repo_name: vectrix-ai/v-router
repo_url: https://github.com/vectrix-ai/v-router
edit_uri: edit/main/docs/

# GitHub Pages configuration
use_directory_urls: true

# Copyright
copyright: Copyright &copy; 2024 Ben Selleslagh

# Configuration
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Customization
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vectrix-ai/v-router
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/v-router/
  generator: false

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"/<>]'

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Function Calling: guide/function-calling.md
    - LangSmith Tracing: guide/langsmith-tracing.md
  - API Reference:
    - Client: api/client.md
    - LLM Configuration: api/llm.md
  - Providers:
    - Overview: providers/overview.md
  - Examples:
    - Basic Examples: examples/basic.md