name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Version Bump and Auto Release"]
    types: [completed]
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    # Only run if the version-bump workflow succeeded OR if manually pushing a tag
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref }}

      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-groups

      - name: Build wheel
        run: uv build

      - name: Publish package
        run: uv publish
